apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: raghad37/ci-cd-lab
    newTag: v4

patches:
  - target:
      kind: Rollout
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: production
